### PR TITLE
Change the boot partition name to resin-boot

### PR DESCRIPTION
**Pull request by agherzan**
Signed-off-by: Andrei Gherzan <andrei@resin.io>

### CODE REVIEW

**Comment by lifeeth** [comment]
Please dont merge till https://bitbucket.org/rulemotion/meta-resin/pull-request/69/beaglebone-reborn is deployed to production.

**Comment by agherzan** [comment]
I don't think I have permissions to merge anyway. I'm safe :)

**Comment by shaunmulligan** [comment]
@lifeeth and @agherzan I guess this can be merged now right?

**Comment by agherzan** [comment]
Yup. Good to merge

**Pull request merged**
