### PR TITLE
headroom-js: previous module was merged into new one, bump version

### PR DESCRIPTION
**Pull request by imrehg**
Referring to #287

### CODE REVIEW

**Comment by emirotin** [comment]
This does not fix the thing, unfortunately — the package does not contain the files we reference from HML. 
Please leave it to me to finish.

**Comment by emirotin** [comment]
Related issue: https://github.com/WickyNilliams/headroom.js/issues/240 (mentions the fix, I'm trying it now)

**Comment by imrehg** [comment]
Strange it created for me...

**Comment by emirotin** [comment]
```
✔ ls static/bower_components/headroom.js
LICENSE      README.md    bower.json   package.json
```

no `dist` folder (and no `src` as well)

**Pull request merged**
