### PR TITLE
Add rpi3 to Nav

### PR DESCRIPTION
**Pull request by craig-mulligan**

### CODE REVIEW

**Comment by emirotin** [comment]
add Zero as well?

**Comment by craig-mulligan** [comment]
Or maybe we just put `Raspberry Pi` because we support all?

**Comment by emirotin** [comment]
yeah. maybe `(all models)`

**Comment by shaunmulligan** [comment]
yeah, i think (all models) will be good

**Comment by shaunmulligan** [comment]
I think we can close this one now as it will get fixed in the switch to metalsmith

**Pull request closed without merging**
