### PR TITLE
Update CLI docs.

### PR DESCRIPTION
**Pull request by lorenzo-stoakes**
The latest CLI doc updates as pulled in from index.sh, separating out from other PR I'm submitting for clarity :)

### CODE REVIEW

**Comment by emirotin** [comment]
It has the changes from that commit as well. Should you rebase?

**Comment by lorenzo-stoakes** [comment]
@emirotin Hm the other PR should have been merged by me :S, approve (LGTM) then merge as in bitbucket. This one needed to be merged first! The other PR is based on this one. I'll rebase again.

**Comment by emirotin** [comment]
Oh sorry :( Fpr some reason I thought for docs PRs are merged by approvers

**Comment by lorenzo-stoakes** [comment]
@emirotin sorry to make an example out of this :P but I think it's important to raise more generally, it's not _that_ big a deal here, but life will be easier if we stick to that

**Comment by lorenzo-stoakes** [comment]
This branch has accidentally had another branch applied against it. Closing, and sending the 2 branches separately again.

**Pull request closed without merging**
