### PR TITLE
add note about dbus mount point for > resinOS v2

### PR DESCRIPTION
**Pull request by craig-mulligan**
We should definitely add resinOS vs into the docs matrix. @shaunmulligan I'll create an issue if you agree?

### CODE REVIEW

**Comment by craig-mulligan** [comment]
Second thought this maybe better to PR into the resinOS docs, and only add v2 specifics once it's released on production?

**Comment by imrehg** [comment]
@craig-mulligan @shaunmulligan sorry, didn't see that it was here (wasn't linked from the issue), and made this update #431
Either one is good for me :)

**Comment by shaunmulligan** [comment]
@craig-mulligan we should probably get people to use `/host/run/dbus` on 1.x now anyways. so it might be worth changing the doc to say use that and if you are on less than 1.13 (or whatever it is) then we should use the old path.

**Comment by craig-mulligan** [comment]
@shaunmulligan Cool, I had a look through the [meta-resin changelog](https://github.com/resin-os/meta-resin/blob/master/CHANGELOG.md) but didn't see any mention of it?

**Comment by shaunmulligan** [comment]
@craig-mulligan the supervisor adds all the bind-mounts to the user containers, so its most likely tied to a specific supervisor version.

**Comment by craig-mulligan** [comment]
Lets go with Gregley PR #431 closing this one.

**Pull request closed without merging**
