### PR TITLE
Feature/dockerfile templates

### PR DESCRIPTION
**Pull request by shaunmulligan**

### CODE REVIEW

**Comment by shaunmulligan** [comment]
Don't merge until device-type and base images naming align

**Comment by craig-mulligan** [comment]
@shaun Perhaps could do with a link to your multi-device app at the end?

**Comment by shaunmulligan** [comment]
@craig-mulligan this has been updated to reflect the RESIN_MACHINE_NAME variable rather than the device type

**Comment by shaunmulligan** [comment]
i will try add my multi-arch ADC app later, it needs one change for it to work i think

**Pull request merged**
