### PR TITLE
Not actually a wiki

### PR DESCRIPTION
**Pull request by sonyagreen**
Docs is a more accurate word

### CODE REVIEW

**Comment by sonyagreen** [comment]
Oh, I'm not sure if the name will get picked up where it's being referenced (sidebar, top nav) by the # or if that requires a separate change somewhere.

**Comment by lurch** [comment]
From a quick scan through the [search results](https://github.com/resin-io/docs/search?utf8=%E2%9C%93&q=wiki&type=Code) it looks like [config/navigation.txt](https://github.com/resin-io/docs/blob/master/config/navigation.txt) and [pages/introduction.md](https://github.com/resin-io/docs/blob/master/pages/introduction.md) might need to be updated in concert?

**Comment by imrehg** [comment]
@sonyagreen @lurch 
In this particular case I went ahead and fixed the mentioned issue (won't normally push onto other people's PR, but here it felt appropriate to fix up the uncovered errors, let me know if I'm wrong!

* `pages/introduction.md` updated
* in the `navigation.txt` one can just remove the page name (see change), and then it will be pulled from the actual markdown file. For most pages that should be the default, unless we want to prevent overflow in the navigation.

**Comment by shaunmulligan** [comment]
LGTM

**Pull request merged**
