### PR TITLE
Make images wiki prominent

### PR DESCRIPTION
**Pull request by lorenzo-stoakes**
Increase prominence of Resin Base Images Wiki
    
Previously this was not so easily accessible, these changes rename the page to make use of the phrase 'base image' which is the more commonly known name for images, add a link to the page on the references tab and add a blurb about base images with a link to the introduction page.
    
Solves issue #248.

### CODE REVIEW

**Comment by emirotin** [comment]
Oh, there's an issue with multiple links to the same page from navigation. If you want it in references you should remove it from the Runtime section

**Comment by lorenzo-stoakes** [comment]
Ah damn @emirotin will remove it from runtime

**Comment by lorenzo-stoakes** [comment]
@emirotin done

**Comment by emirotin** [comment]
Just to put the context, the issue is that if the page appears twice it's impossible to detect its _true_ position in the tree (the last occurrence will be used). It leads to strange behaviour when you click on the link corresponding to the first occurrence, and see the page whose breadcrumbs and sidebar nav reflect its position according to the last occurrence.

**Comment by emirotin** [comment]
LGTM.
Please remember that merging it will auto-deploy to the preview site. To deploy to production we have then to merge the master into production.

**Comment by lorenzo-stoakes** [comment]
Cool cheers, will wait on @shaunmulligan for a final OK on the content first.

**Comment by shaunmulligan** [comment]
@lorenzo-stoakes LGTM

**Pull request merged**
